import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import Topnav from "@/components/navbar/TopNav";

export const metadata: Metadata = {
  title: "NextMatch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Topnav />
            <main className="container ms-auto p-10">
              {children}
            </main>
        </Providers>
      </body>
    </html>
  );
}
